import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "../sass/main.scss";
import { Header } from "@/components/layout/Header";
import { getGlobalSettings } from "@/data/loaders";
import { notFound } from "next/navigation";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function loader() {
  const globalSettings = await getGlobalSettings();
  console.log("Global settings data:", globalSettings);

  const header = globalSettings?.data?.header?.[0];

  return { header };
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const { header } = await loader();
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
      <Header data={header} />
        {children}
      </body>
    </html>
  );
}
